name: caresync
description: A Flutter application for healthcare services.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  google_sign_in: ^6.1.0
  firebase_storage: ^12.4.5
  file_picker: ^10.1.2
  flutter_local_notifications: ^19.1.0
  flutter_localizations:
    sdk: flutter
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  intl: ^0.19.0
  path_provider: ^2.0.14
  timezone: ^0.10.0
  http: ^1.3.0
  flutter_dotenv: ^5.1.0
  image_picker: ^0.8.7+4
  shared_preferences: ^2.0.15
  easy_localization: ^3.0.0
  flutter_launcher_icons: ^0.14.3
  open_file: ^3.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/google_logo.png
    - assets/.env
    - assets/translations/
    - assets/images/A_splash_screen_for_CareSync.png
    - assets/images/app_icon.png